version: '3'
services:
  postgres_server:
    image: "postgres:15.3-alpine3.18"
    container_name: postgres_cryptos_container
    restart: "always"
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - ./backend/postgres:/var/lib/postgresql/data
  backend:
    build: ./backend
    container_name: nestjs_api
    restart: always
    ports:
      - '5000:5000'
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres_server



