version: '3'
services:
  postgres_server:
    image: "postgres:15.3-alpine3.18"
    container_name: postgres-dev_container
    restart: on-failure
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data