version: '3'
services:
  postgres:
    image: "postgres:15.3-alpine3.18"
    container_name: postgres_cryptos_container
    restart: "unless-stopped"
    environment:
      - POSTGRES_DB=$POSTGRES_DB_NAME
      - POSTGRES_USER=$POSTGRES_DB_USERNAME
      - POSTGRES_PASSWORD=$POSTGRES_DB_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data


