export const DATA_SOURCE = 'DATA_SOURCE'
export const ARTICLE_REPOSITORY = 'ARTICLE_REPOSITORY'
export const USER_REPOSITORY = 'USER_REPOSITORY'
export const TOKEN_REPOSITORY = 'TOKEN_REPOSITORY'

export const MAILER_CONFIG = 'MAILER_CONFIG'
